# README #

taskr is an ongoing implementation of a client for the upcoming taskr todo managment platform

## Build ##

You need a properly configured `settings.properties`. Copy the included `settings.properties.template`, rename it and configure the domain in the file.

The just run `ant`.